## Euler Rotations

In this notebook you'll explore Euler rotations and get a feel for why the order of rotations matters.

Euler rotations as we define them in this program are counterclockwise about the axes of the vehicle body frame, where:

- *Roll* - $\phi$ is about the x-axis
- *Pitch* - $\theta$ is about the y-axis
- *Yaw* - $\psi$ is about the z-axis

As you'll see the same set of rotation transformations, applied in a different order can produce a very different final result!

In [1]:
import matplotlib.pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D

import numpy as np
from enum import Enum

%matplotlib inline
np.set_printoptions(precision=3, suppress=True)

In [2]:
plt.rcParams["figure.figsize"] = [12, 12]

In [42]:
class Rotation(Enum):
    ROLL = 0
    PITCH = 1
    YAW = 2  


class EulerRotation:
    
    def __init__(self, rotations):
        """
        `rotations` is a list of 2-element tuples where the
        first element is the rotation kind and the second element
        is angle in degrees.
        
        Ex:
        
            [(Rotation.ROLL, 45), (Rotation.YAW, 32), (Rotation.PITCH, 55)]
            
        """
        self._rotations = rotations
        self._rotation_map = {Rotation.ROLL :(0, self.roll), Rotation.PITCH : (1,self.pitch), Rotation.YAW : (2,self.yaw)}

    def roll(self, phi):
        """Returns a rotation matrix along the roll axis"""
        R_roll = np.array([
            [1 , 0 , 0 ],
            [0 , np.cos(phi) , -np.sin(phi)],
            [0 , np.sin(phi) , np.cos(phi)]
        ])
        return R_roll
    
    def pitch(self, theta):
        """Returns the rotation matrix along the pitch axis"""
        R_pitch = np.array([
            [np.cos(theta) , 0 , np.sin(theta)],
            [0 , 1 , 0],
            [-np.sin(theta) , 0 , np.cos(theta)]
        ])
        return R_pitch

    def yaw(self, psi):
        """Returns the rotation matrix along the yaw axis"""
        R_yaw=np.array([
            [np.cos(psi) , -np.sin(psi) , 0],
            [np.sin(psi) , np.cos(psi) , 0],
            [0 , 0 ,1]
        ])
        return R_yaw

    def rotate(self):
        angle=1.0
        """Applies the rotations in sequential order"""
        for rotation in self._rotations:
            axis=rotation[0]
            angle=rotation[1]
            angle_rad=np.deg2rad(angle)
            (order,func)= self._rotation_map[axis]
            if(order ==0):
                roll = func.__call__(angle_rad)
                print("roll",roll)
            if(order==1):
                pitch = func.__call__(angle_rad)
                print("Pitch",pitch)
            if(order==2):
                yaw = self.yaw(angle_rad)
                print("yaw",yaw)
            
        Mat = yaw @ pitch @ roll
        return Mat

Below you'll form a sequence of rotations. The rotation matrix `R` is the mapping of performing the rotations in sequential order. Multiplying a vector by `R` will perform the rotations on that vector.

In [43]:
# Test your code by passing in some rotation values
rotations = [
    (Rotation.ROLL, 25),
    (Rotation.PITCH, 75),
    (Rotation.YAW,90 ),
]

R = EulerRotation(rotations).rotate()
print('Rotation matrix ...')
print(R)
# Should print
# Rotation matrix ...
# [[ 0.    -0.906  0.423]
#  [ 0.259  0.408  0.875]
#  [-0.966  0.109  0.235]]

roll [[ 1.     0.     0.   ]
 [ 0.     0.906 -0.423]
 [ 0.     0.423  0.906]]
Pitch [[ 0.259  0.     0.966]
 [ 0.     1.     0.   ]
 [-0.966  0.     0.259]]
yaw [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
Rotation matrix ...
[[ 0.    -0.906  0.423]
 [ 0.259  0.408  0.875]
 [-0.966  0.109  0.235]]


Go back and change the order of the rotations, you should get back a rotation matrix with different values.

### Same Rotations, Different Order

Now calculate three different rotations matrices. They should stem from the same set of Euler rotations, just in differing order.

In [ ]:
# TODO: calculate 3 rotation matrices.
R1 = None
R2 = None
R3 = None

### Seeing is Believing

It's clear the three rotation matrices are different, but, in order to get an deeper understanding let's plot the impact of the rotations.

In [ ]:
# unit vector along x-axis
v = np.array([1, 0, 0])

Apply the rotations to `v`. Feel free to change the values of this input vector.

In [ ]:
# TODO: calculate the new rotated versions of `v`.
rv1 = None
rv2 = None
rv3 = None
# rv = np.dot(R, v)

Plotting time ...

In [ ]:
fig = plt.figure()
ax = fig.gca(projection='3d')

# axes (shown in black)
ax.quiver(0, 0, 0, 1.5, 0, 0, color='black', arrow_length_ratio=0.15)
ax.quiver(0, 0, 0, 0, 1.5, 0, color='black', arrow_length_ratio=0.15)
ax.quiver(0, 0, 0, 0, 0, 1.5, color='black', arrow_length_ratio=0.15)


# Original Vector (shown in blue)
ax.quiver(0, 0, 0, v[0], v[1], v[2], color='blue', arrow_length_ratio=0.15)

# Rotated Vectors (shown in red)
ax.quiver(0, 0, 0, rv1[0], rv1[1], rv1[2], color='red', arrow_length_ratio=0.15)
ax.quiver(0, 0, 0, rv2[0], rv2[1], rv2[2], color='purple', arrow_length_ratio=0.15)
ax.quiver(0, 0, 0, rv3[0], rv3[1], rv3[2], color='green', arrow_length_ratio=0.15)

ax.set_xlim3d(-1, 1)
ax.set_ylim3d(1, -1)
ax.set_zlim3d(1, -1)

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

plt.show()

### Gimbal Lock
To demonstrate gimbal lock try starting a series of rotations with a pitch of +/- 90 degrees, then see what happens when you try to yaw. Try the yaw first and see what happens!

[solution](/notebooks/Rotations-Solution.ipynb)